include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  errors:
    # Too many exceptions
    comment_references: ignore
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - avoid_private_typedef_functions
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_runtimeType_toString
    - prefer_const_declarations
    - unnecessary_await_in_return
    - use_string_buffers
