name: oauth2
version: 2.0.5
description: >-
  A client library for authenticating with a remote service via OAuth2 on
  behalf of a user, and making authorized HTTP requests with the user's
  OAuth2 credentials.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/oauth2
issue_tracker: https://github.com/dart-lang/tools/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Aoauth2
  
environment:
  sdk: ^3.4.0

dependencies:
  collection: ^1.15.0
  crypto: ^3.0.0
  http: ^1.0.0
  http_parser: ^4.0.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.0
