include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-raw-types: true
    strict-inference: true
    strict-casts: true

linter:
  rules:
    - prefer_final_in_for_each
    - prefer_final_locals
