name: language_version
description: >-
  A library with a type to represent a Dart language version.
version: 0.1.0-wip
repository: https://github.com/dart-lang/tools/tree/main/pkgs/language_version
issue_tracker: https://github.com/dart-lang/tools/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Alanguage_version

environment:
  sdk: ^3.3.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.24.0
