name: markdown
version: 7.3.1-wip
description: >-
  A portable Markdown library written in Dart that can parse Markdown into HTML.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/markdown
issue_tracker: https://github.com/dart-lang/tools/labels/package%3Amarkdown

topics:
  - markdown

executables:
  markdown:

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.5
  build_version: ^2.0.3
  build_web_compilers: ^4.0.0
  collection: ^1.15.0
  dart_flutter_team_lints: ^3.0.0
  html: ^0.15.0
  http: ^1.0.0
  io: ^1.0.0
  path: ^1.8.0
  pool: ^1.5.1
  tar: ^1.0.3
  test: ^1.16.0
  web: ^1.0.0
  yaml: ^3.0.0
