name: benchmark_harness
version: 2.3.1
description: The official Dart project benchmark harness.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/benchmark_harness
issue_tracker: https://github.com/dart-lang/tools/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Abenchmark_harness

topics:
 - benchmarking

environment:
  sdk: ^3.2.0

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^4.0.0
  dart_flutter_team_lints: ^3.0.0
  path: ^1.8.0
  test: ^1.16.0
