include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  errors:
    inference_failure_on_collection_literal: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_function_return_type: ignore
    inference_failure_on_instance_creation: ignore
