name: clock
version: 1.1.3-wip
description: A fakeable wrapper for dart:core clock APIs.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/clock
issue_tracker: https://github.com/dart-lang/tools/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Aclock

environment:
  sdk: ^3.4.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.6
