name: pubspec_parse
version: 1.5.0
description: >-
  Simple package for parsing pubspec.yaml files with a type-safe API and rich
  error reporting.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/pubspec_parse

topics:
- dart-pub

environment:
  sdk: ^3.6.0

dependencies:
  checked_yaml: ^2.0.1
  collection: ^1.19.0
  json_annotation: ^4.9.0
  pub_semver: ^2.1.4
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.0.0
  dart_flutter_team_lints: ^3.0.0
  json_serializable: ^6.9.1
  path: ^1.9.0
  # Needed because we are configuring `combining_builder`
  source_gen: ^2.0.0
  stack_trace: ^1.10.0
  test: ^1.24.4
  test_descriptor: ^2.0.0
  test_process: ^2.0.0
