// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// Client for verifying Sigstore signatures and managing trusted root material.
final class SigstoreClient implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  SigstoreClient._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _sigstore_SigstoreClient_destroy_mv1(this, _ffi.cast());
    }
  }

  // ignore: experimental_member_use
  @meta.RecordUse()
  // ignore: non_constant_identifier_names
  static void _sigstore_SigstoreClient_destroy_mv1(SigstoreClient cl, ffi.Pointer<ffi.Void> pointer) => _finalizer.attach(cl, pointer);

  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_internal_sigstore_SigstoreClient_destroy_mv1));

  /// Creates a new Sigstore client instance.
  static SigstoreClient create() {
    final result = _sigstore_SigstoreClient_create_mv1();
    return SigstoreClient._fromFfi(result, []);
  }

  /// Verifies an artifact against a Sigstore bundle and verification policy.
  ///
  /// - `artifact_bytes`: Raw artifact bytes, or precomputed SHA-256 digest bytes if `is_digest` is true.
  /// - `is_digest`: Set to `true` if `artifact_bytes` contains the precomputed SHA-256 digest (32 bytes).
  /// - `bundle`: The parsed bundle containing signatures and verification material.
  /// - `policy`: The verification policy specifying expected identity, issuer, and trusted root.
  ///
  /// Throws [SigstoreError] on failure.
  SigstoreVerificationResult verify(core.List<int> artifactBytes, bool isDigest, SigstoreBundle bundle, SigstoreVerificationPolicy policy) {
    final temp = _FinalizedArena();
    final result = _sigstore_SigstoreClient_verify_mv1(_ffi, artifactBytes._uint8AllocIn(temp.arena), isDigest, bundle._ffi, policy._ffi);
    if (!result.isOk) {
      throw SigstoreError.values[result.union.err];
    }
    return SigstoreVerificationResult._fromFfi(result.union.ok, []);
  }

  /// Refreshes the TUF trusted root from the Sigstore TUF mirror into `cache_dir` using full TUF verification.
  ///
  /// - `tuf_mirror_url`: URL of the Sigstore TUF repository mirror (e.g. `https://tuf-repo-cdn.sigstore.dev`).
  /// - `cache_dir`: Local filesystem directory path to cache downloaded TUF metadata and targets.
  ///
  /// Returns the verified `trusted_root.json` string.
  ///
  /// Throws [SigstoreError] on failure.
  String refreshTrustedRoot(String tufMirrorUrl, String cacheDir) {
    final temp = _FinalizedArena();
    final write = _Write();
    final result = _sigstore_SigstoreClient_refresh_trusted_root_mv1(_ffi, tufMirrorUrl._utf8AllocIn(temp.arena), cacheDir._utf8AllocIn(temp.arena), write._ffi);
    if (!result.isOk) {
      throw SigstoreError.values[result.union.err];
    }
    return write.finalize();
  }

}

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'sigstore_SigstoreClient_destroy_mv1')
// ignore: non_constant_identifier_names
external void _internal_sigstore_SigstoreClient_destroy_mv1(ffi.Pointer<ffi.Void> self);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<ffi.Pointer<ffi.Opaque> Function()>(isLeaf: true, symbol: 'sigstore_SigstoreClient_create_mv1')
// ignore: non_constant_identifier_names
external ffi.Pointer<ffi.Opaque> _sigstore_SigstoreClient_create_mv1();

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<_ResultOpaqueInt32 Function(ffi.Pointer<ffi.Opaque>, _SliceUint8, ffi.Bool, ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'sigstore_SigstoreClient_verify_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _sigstore_SigstoreClient_verify_mv1(ffi.Pointer<ffi.Opaque> self, _SliceUint8 artifactBytes, bool isDigest, ffi.Pointer<ffi.Opaque> bundle, ffi.Pointer<ffi.Opaque> policy);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<_ResultVoidInt32 Function(ffi.Pointer<ffi.Opaque>, _SliceUtf8, _SliceUtf8, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'sigstore_SigstoreClient_refresh_trusted_root_mv1')
// ignore: non_constant_identifier_names
external _ResultVoidInt32 _sigstore_SigstoreClient_refresh_trusted_root_mv1(ffi.Pointer<ffi.Opaque> self, _SliceUtf8 tufMirrorUrl, _SliceUtf8 cacheDir, ffi.Pointer<ffi.Opaque> write);

// dart format on
