// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// A Sigstore bundle containing signature material, verification material (such as X.509 certificates
/// or public key hints), and transparency log inclusion proofs.
final class SigstoreBundle implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  SigstoreBundle._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _sigstore_SigstoreBundle_destroy_mv1(this, _ffi.cast());
    }
  }

  // ignore: experimental_member_use
  @meta.RecordUse()
  // ignore: non_constant_identifier_names
  static void _sigstore_SigstoreBundle_destroy_mv1(SigstoreBundle cl, ffi.Pointer<ffi.Void> pointer) => _finalizer.attach(cl, pointer);

  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_internal_sigstore_SigstoreBundle_destroy_mv1));

  /// Parses a Sigstore bundle from a JSON string.
  ///
  /// Throws [SigstoreError] on failure.
  static SigstoreBundle fromJson(String json) {
    final temp = _FinalizedArena();
    final result = _sigstore_SigstoreBundle_from_json_mv1(json._utf8AllocIn(temp.arena));
    if (!result.isOk) {
      throw SigstoreError.values[result.union.err];
    }
    return SigstoreBundle._fromFfi(result.union.ok, []);
  }

  /// Serializes the Sigstore bundle to a JSON string.
  ///
  /// Throws [SigstoreError] on failure.
  String toJson() {
    final write = _Write();
    final result = _sigstore_SigstoreBundle_to_json_mv1(_ffi, write._ffi);
    if (!result.isOk) {
      throw SigstoreError.values[result.union.err];
    }
    return write.finalize();
  }

  /// Returns the certificate subject (subject alternative name email or URI) from the signing certificate.
  ///
  /// Throws [SigstoreError] on failure.
  String getCertificateSubject() {
    final write = _Write();
    final result = _sigstore_SigstoreBundle_get_certificate_subject_mv1(_ffi, write._ffi);
    if (!result.isOk) {
      throw SigstoreError.values[result.union.err];
    }
    return write.finalize();
  }

  /// Returns the OIDC issuer URL from the signing certificate extensions.
  ///
  /// Throws [SigstoreError] on failure.
  String getCertificateIssuer() {
    final write = _Write();
    final result = _sigstore_SigstoreBundle_get_certificate_issuer_mv1(_ffi, write._ffi);
    if (!result.isOk) {
      throw SigstoreError.values[result.union.err];
    }
    return write.finalize();
  }

  /// Returns the Rekor transparency log index if present, or `-1` if no log entry is present.
  int getRekorLogIndex() {
    final result = _sigstore_SigstoreBundle_get_rekor_log_index_mv1(_ffi);
    return result;
  }

}

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'sigstore_SigstoreBundle_destroy_mv1')
// ignore: non_constant_identifier_names
external void _internal_sigstore_SigstoreBundle_destroy_mv1(ffi.Pointer<ffi.Void> self);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<_ResultOpaqueInt32 Function(_SliceUtf8)>(isLeaf: true, symbol: 'sigstore_SigstoreBundle_from_json_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _sigstore_SigstoreBundle_from_json_mv1(_SliceUtf8 json);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<_ResultVoidInt32 Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'sigstore_SigstoreBundle_to_json_mv1')
// ignore: non_constant_identifier_names
external _ResultVoidInt32 _sigstore_SigstoreBundle_to_json_mv1(ffi.Pointer<ffi.Opaque> self, ffi.Pointer<ffi.Opaque> write);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<_ResultVoidInt32 Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'sigstore_SigstoreBundle_get_certificate_subject_mv1')
// ignore: non_constant_identifier_names
external _ResultVoidInt32 _sigstore_SigstoreBundle_get_certificate_subject_mv1(ffi.Pointer<ffi.Opaque> self, ffi.Pointer<ffi.Opaque> write);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<_ResultVoidInt32 Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'sigstore_SigstoreBundle_get_certificate_issuer_mv1')
// ignore: non_constant_identifier_names
external _ResultVoidInt32 _sigstore_SigstoreBundle_get_certificate_issuer_mv1(ffi.Pointer<ffi.Opaque> self, ffi.Pointer<ffi.Opaque> write);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<ffi.Int64 Function(ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'sigstore_SigstoreBundle_get_rekor_log_index_mv1')
// ignore: non_constant_identifier_names
external int _sigstore_SigstoreBundle_get_rekor_log_index_mv1(ffi.Pointer<ffi.Opaque> self);

// dart format on
