// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// Errors that can occur during Sigstore bundle parsing, verification, or root refresh.
enum SigstoreError {
  /// The bundle is structurally invalid, cannot be parsed from JSON, or contains malformed verification material.
  invalidBundle,
  /// Cryptographic verification failed.
  ///
  /// This can happen if the signature does not match, the certificate does not chain to the trusted root,
  /// the identity or issuer does not match policy expectations, or transparency log proofs fail.
  verificationFailed,
  /// An internal error occurred during verification or cryptographic operations.
  internalError;

}

// dart format on
