// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// Policy configuration specifying expected signing identity, issuer, trusted root, and network options for verification.
final class SigstoreVerificationPolicy implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  SigstoreVerificationPolicy._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _sigstore_SigstoreVerificationPolicy_destroy_mv1(this, _ffi.cast());
    }
  }

  // ignore: experimental_member_use
  @meta.RecordUse()
  // ignore: non_constant_identifier_names
  static void _sigstore_SigstoreVerificationPolicy_destroy_mv1(SigstoreVerificationPolicy cl, ffi.Pointer<ffi.Void> pointer) => _finalizer.attach(cl, pointer);

  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_internal_sigstore_SigstoreVerificationPolicy_destroy_mv1));

  /// Creates a new verification policy.
  ///
  /// - `expected_identity`: Expected certificate subject (SAN email or URI). If empty, identity is not restricted.
  /// - `expected_issuer`: Expected OIDC issuer URL (e.g. `https://token.actions.githubusercontent.com`). If empty, issuer is not restricted.
  /// - `offline`: Whether to perform verification offline without network access.
  /// - `is_staging`: Whether to verify against Sigstore's staging environment instead of production.
  /// - `trusted_root_json`: Optional custom trusted root JSON string. If empty, the default Sigstore root is used.
  /// - `public_key_pem`: Optional PEM-encoded public key for verifying bundles created with pre-shared keys.
  ///
  /// Throws [SigstoreError] on failure.
  static SigstoreVerificationPolicy create(String expectedIdentity, String expectedIssuer, bool offline, bool isStaging, String trustedRootJson, String publicKeyPem) {
    final temp = _FinalizedArena();
    final result = _sigstore_SigstoreVerificationPolicy_create_mv1(expectedIdentity._utf8AllocIn(temp.arena), expectedIssuer._utf8AllocIn(temp.arena), offline, isStaging, trustedRootJson._utf8AllocIn(temp.arena), publicKeyPem._utf8AllocIn(temp.arena));
    if (!result.isOk) {
      throw SigstoreError.values[result.union.err];
    }
    return SigstoreVerificationPolicy._fromFfi(result.union.ok, []);
  }

}

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'sigstore_SigstoreVerificationPolicy_destroy_mv1')
// ignore: non_constant_identifier_names
external void _internal_sigstore_SigstoreVerificationPolicy_destroy_mv1(ffi.Pointer<ffi.Void> self);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<_ResultOpaqueInt32 Function(_SliceUtf8, _SliceUtf8, ffi.Bool, ffi.Bool, _SliceUtf8, _SliceUtf8)>(isLeaf: true, symbol: 'sigstore_SigstoreVerificationPolicy_create_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _sigstore_SigstoreVerificationPolicy_create_mv1(_SliceUtf8 expectedIdentity, _SliceUtf8 expectedIssuer, bool offline, bool isStaging, _SliceUtf8 trustedRootJson, _SliceUtf8 publicKeyPem);

// dart format on
