// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// The result of verifying an artifact against a Sigstore bundle and verification policy.
final class SigstoreVerificationResult implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  SigstoreVerificationResult._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _sigstore_SigstoreVerificationResult_destroy_mv1(this, _ffi.cast());
    }
  }

  // ignore: experimental_member_use
  @meta.RecordUse()
  // ignore: non_constant_identifier_names
  static void _sigstore_SigstoreVerificationResult_destroy_mv1(SigstoreVerificationResult cl, ffi.Pointer<ffi.Void> pointer) => _finalizer.attach(cl, pointer);

  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_internal_sigstore_SigstoreVerificationResult_destroy_mv1));

  /// Returns `true` if the artifact signature and verification materials are valid.
  bool isValid() {
    final result = _sigstore_SigstoreVerificationResult_is_valid_mv1(_ffi);
    return result;
  }

  /// Returns the verified signing identity (subject alternative name email or URI) from the certificate.
  ///
  /// Throws [SigstoreError] on failure.
  String verifiedIdentity() {
    final write = _Write();
    final result = _sigstore_SigstoreVerificationResult_verified_identity_mv1(_ffi, write._ffi);
    if (!result.isOk) {
      throw SigstoreError.values[result.union.err];
    }
    return write.finalize();
  }

  /// Returns the verified OIDC issuer URL from the signing certificate extensions.
  ///
  /// Throws [SigstoreError] on failure.
  String verifiedIssuer() {
    final write = _Write();
    final result = _sigstore_SigstoreVerificationResult_verified_issuer_mv1(_ffi, write._ffi);
    if (!result.isOk) {
      throw SigstoreError.values[result.union.err];
    }
    return write.finalize();
  }

}

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'sigstore_SigstoreVerificationResult_destroy_mv1')
// ignore: non_constant_identifier_names
external void _internal_sigstore_SigstoreVerificationResult_destroy_mv1(ffi.Pointer<ffi.Void> self);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'sigstore_SigstoreVerificationResult_is_valid_mv1')
// ignore: non_constant_identifier_names
external bool _sigstore_SigstoreVerificationResult_is_valid_mv1(ffi.Pointer<ffi.Opaque> self);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<_ResultVoidInt32 Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'sigstore_SigstoreVerificationResult_verified_identity_mv1')
// ignore: non_constant_identifier_names
external _ResultVoidInt32 _sigstore_SigstoreVerificationResult_verified_identity_mv1(ffi.Pointer<ffi.Opaque> self, ffi.Pointer<ffi.Opaque> write);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<_ResultVoidInt32 Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'sigstore_SigstoreVerificationResult_verified_issuer_mv1')
// ignore: non_constant_identifier_names
external _ResultVoidInt32 _sigstore_SigstoreVerificationResult_verified_issuer_mv1(ffi.Pointer<ffi.Opaque> self, ffi.Pointer<ffi.Opaque> write);

// dart format on
