name: dash_analytics
description: A package for logging analytics for all dash related tooling to Google Analytics
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0-406.0.dev <3.0.0'

dependencies:
  clock: ^1.1.1
  file: ^6.1.4
  http: ^0.13.5
  intl: ^0.17.0
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  yaml: ^3.1.1
