name: dash_analytics
description: >-
  A package for logging analytics for all dash related tooling to Google
  Analytics.
# When updating this, keep the version consistent with the changelog and the
# value in lib/src/constants.dart.
version: 0.1.0-dev
repository: https://github.com/dart-lang/tools/tree/main/pkgs/dash_analytics

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  clock: ^1.1.1
  file: ^6.1.4
  http: ^0.13.5
  intl: ^0.17.0
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  yaml: ^3.1.1
