name: io
version: 1.1.0-wip
description: >-
  Utilities for the Dart VM Runtime including support for ANSI colors, file
  copying, and standard exit code values.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/io
issue_tracker: https://github.com/dart-lang/tools/labels/package%3Aio

environment:
  sdk: ^3.4.0

dependencies:
  meta: ^1.3.0
  path: ^1.8.0
  string_scanner: ^1.1.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.6
  test_descriptor: ^2.0.0
