name: glob
version: 2.1.3
description: A library to perform Bash-style file and directory globbing.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/glob
issue_tracker: https://github.com/dart-lang/tools/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Aglob

environment:
  sdk: ^3.3.0

dependencies:
  async: ^2.5.0
  collection: ^1.15.0
  file: '>=6.1.3 <8.0.0'
  path: ^1.8.0
  string_scanner: ^1.1.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.17.0
  test_descriptor: ^2.0.0
