// Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// coverage:ignore-file
// ignore_for_file: public_member_api_docs

// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN
//
//    dart tool/regenerate_hashes.dart <github tag>
//

const version = 'binaries-v0.1.4';

const fileHashes = <(String, String), String>{
  ('x86_64-unknown-linux-gnu', 'dynamic'):
      '123f684f58d366129ff63250a3f95350b011df26be3a80258405aae8056add00',
  ('x86_64-unknown-linux-gnu', 'static'):
      'a919ba6a3aea7999873c8cfe0337e10894b310706aaa30461e1620492dc8a2c5',
  ('aarch64-apple-darwin', 'dynamic'):
      'c4c4597a61bc9d5b4cd9ff9df8b205234eec505687be431675477475b2a84afc',
  ('aarch64-apple-darwin', 'static'):
      'fc1ec772c2d75607e2bec7398f53279aabbc8254df00656c343b30c1341f268d',
  ('x86_64-pc-windows-msvc', 'dynamic'):
      '5764368c8a499511c65778bb74a71f0f326b334367e1b1a68f04ed7978da487b',
  ('x86_64-pc-windows-msvc', 'static'):
      '4ed2a8ada722132ebadd14e6a067b4217e3a62950bcd4eb3a5624df1aad32a88',
};
