name: hello_world_german
version: 1.0.0
publish_to: none # This is an example, don't publish!

dependencies:
  # We keep a dependency on package `hello_world` because this package provides
  # an extension for this package. Hence, a newer major version of hello_world
  # might be incompatible with the extension options we've provided in
  #   extension/hello_world/config.json
  # It is `hello_world` that specifies what is required in `config.json`.
  hello_world: # ^1.0.0
    path: ../hello_world

environment:
  sdk: ^3.0.0
