// Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// coverage:ignore-file

import 'dart:io';
import 'dart:typed_data';

import 'package:crypto/crypto.dart' show sha256;
import 'package:sigstore/src/hook_helpers/builder.dart';

Future<void> main(List<String> args) async {
  if (args.isEmpty) {
    print('Usage: dart tool/regenerate_hashes.dart <github-release-tag>');
    exit(1);
  }
  final version = args[0];
  final httpClient = HttpClient();

  print('Checking hashes for $version');
  final fileHashes = <(String, String), String>{};
  for (final rustTarget in allTargets) {
    for (final libraryType in ['dynamic', 'static']) {
      final uri = Uri.parse(
        'https://github.com/mosuem/sigstore/releases/'
        'download/$version/libsigstore_ffi-$libraryType-$rustTarget',
      );
      print('Fetching from $uri');
      try {
        final request = await httpClient.getUrl(uri);
        final response = await request.close();
        if (response.statusCode != 200) {
          print('Skipping: not found at $uri');
          continue;
        }
        final builder = BytesBuilder(copy: false);
        await response.forEach(builder.add);
        final bytes = builder.takeBytes();
        final fileHash = sha256.convert(bytes).toString();
        fileHashes[(rustTarget, libraryType)] = fileHash;
        print('Target $rustTarget ($libraryType): $fileHash');
      } catch (e) {
        print('Error fetching $uri: $e');
      }
    }
  }
  httpClient.close(force: true);

  await File('lib/src/hook_helpers/hashes.dart').writeAsString('''
// Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// coverage:ignore-file
// ignore_for_file: public_member_api_docs

// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN
//
//    dart tool/regenerate_hashes.dart <github tag>
//

const version = '$version';

const fileHashes = <(String, String), String>{
${fileHashes.map((key, value) => MapEntry("('${key.$1}', '${key.$2}')", "'$value'")).entries.map((e) => '  ${e.key}:\n      ${e.value},').join('\n')}
};
''');
  print(
    'Updated lib/src/hook_helpers/hashes.dart with ${fileHashes.length} hashes.',
  );
}
