# This file configures the static analysis results for your project (errors,
# warnings, and lints).

include: package:dart_flutter_team_lints/analysis_options.yaml

linter:
  rules:
    - avoid_catches_without_on_clauses
