// Copyright (c) 2026, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// coverage:ignore-file

import 'dart:io';
import 'dart:typed_data';

import 'package:boring/src/hook_helpers/targets.dart';
import 'package:boring/src/hook_helpers/version.dart';
import 'package:crypto/crypto.dart' show sha256;

/// Writes the SHA-256 hashes of the release assets built by
/// tool/precompile_binaries.dart to lib/src/hook_helpers/hashes.dart.
Future<void> main(List<String> args) async {
  final version = args.isNotEmpty ? args[0] : releaseVersion;
  final localDir = args.length > 1 ? Directory(args[1]) : null;
  final httpClient = localDir == null ? HttpClient() : null;

  stdout.writeln('Checking hashes for version $version...');
  final fileHashes = <String, String>{};

  for (final (os, arch, iosSdk) in supportedTargets) {
    for (final static in [false, true]) {
      final assetName = releaseAssetName(
        os,
        arch,
        iosSdk: iosSdk,
        static: static,
      );
      if (localDir != null) {
        final file = File('${localDir.path}/$assetName');
        if (!await file.exists()) {
          stdout.writeln('  Skipping missing local file: ${file.path}');
          continue;
        }
        final fileHash = sha256.convert(await file.readAsBytes()).toString();
        fileHashes[assetName] = fileHash;
        stdout.writeln('  $assetName: $fileHash');
        continue;
      }

      final uri = Uri.parse(
        'https://github.com/mosuem/boring/releases/download/v$version/$assetName',
      );

      stdout.writeln('Fetching from $uri...');
      try {
        final request = await httpClient!.getUrl(uri);
        final response = await request.close();
        if (response.statusCode != 200) {
          stdout.writeln('  Skipping: status ${response.statusCode}');
          await response.drain<void>();
          continue;
        }
        final builder = BytesBuilder(copy: false);
        await response.forEach(builder.add);
        final fileHash = sha256.convert(builder.takeBytes()).toString();
        fileHashes[assetName] = fileHash;
        stdout.writeln('  $assetName: $fileHash');
      } catch (e) {
        stdout.writeln('  Error fetching $uri: $e');
      }
    }
  }
  httpClient?.close(force: true);

  await File('lib/src/hook_helpers/version.dart').writeAsString(
    '// Copyright (c) 2026, the Dart project authors. Please see the AUTHORS '
    'file\n'
    '// for details. All rights reserved. Use of this source code is governed '
    'by a\n'
    '// BSD-style license that can be found in the LICENSE file.\n'
    '\n'
    "const releaseVersion = '$version';\n",
  );

  final buffer = StringBuffer()
    ..writeln(
      '// Copyright (c) 2026, the Dart project authors. Please see the AUTHORS '
      'file',
    )
    ..writeln(
      '// for details. All rights reserved. Use of this source code is '
      'governed by a',
    )
    ..writeln('// BSD-style license that can be found in the LICENSE file.')
    ..writeln()
    ..writeln('// coverage:ignore-file')
    ..writeln('// THIS FILE IS GENERATED BY `tool/regenerate_hashes.dart`.')
    ..writeln()
    ..writeln("import 'version.dart';")
    ..writeln()
    ..writeln('const version = releaseVersion;')
    ..writeln()
    ..writeln('/// Mapping from release asset name (see `releaseAssetName`) to')
    ..writeln('/// SHA-256 hash.')
    ..writeln('const fileHashes = <String, String>{');

  for (final entry in fileHashes.entries) {
    buffer.writeln("  '${entry.key}':");
    buffer.writeln("      '${entry.value}',");
  }
  buffer.writeln('};');

  await File(
    'lib/src/hook_helpers/hashes.dart',
  ).writeAsString(buffer.toString());
  await Process.run(Platform.resolvedExecutable, [
    'format',
    'lib/src/hook_helpers/version.dart',
    'lib/src/hook_helpers/hashes.dart',
  ]);
  stdout.writeln(
    'Updated lib/src/hook_helpers/hashes.dart with ${fileHashes.length} hashes.',
  );
}
