name: file_testing
version: 3.0.1
description: Testing utilities for package:file.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/file_testing

environment:
  sdk: ^3.0.0

dependencies:
  test: ^1.23.1

dev_dependencies: 
  lints: ^2.0.1
