name: file_testing
version: 3.0.2
description: Testing utilities for package:file.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/file_testing
issue_tracker: https://github.com/dart-lang/tools/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Afile_testing

environment:
  sdk: ^3.1.0

dependencies:
  test: ^1.23.1

dev_dependencies: 
  lints: ^5.0.0
