name: stream_transform
version: 2.1.2-wip
description: A collection of utilities to transform and manipulate streams.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/stream_transform
issue_tracker: https://github.com/dart-lang/tools/labels/package%3Astream_transform

environment:
  sdk: ^3.4.0

dev_dependencies:
  async: ^2.5.0
  dart_flutter_team_lints: ^3.0.0
  fake_async: ^1.3.0
  test: ^1.16.0
  web: ^1.1.0
