// Copyright (c) 2026, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// coverage:ignore-file
// THIS FILE IS GENERATED BY `tool/regenerate_hashes.dart`.

/// The version of the release with the prebuilt libraries, see
/// `releaseAssetUrl` in targets.dart.
const version = '0.4.1';

/// Mapping from release asset name (see `releaseAssetName`) to
/// SHA-256 hash.
const fileHashes = <String, String>{
  'boring-linux-arm64-libbssl_dart.so':
      '7a43ec9d900beac0117fb587f52fd18a08aeaadf78338ee7f5dbda06e0f0cefe',
  'boring-linux-arm64-libbssl_dart_static.a':
      'd371bceb29bd51e44a5b5f232a10d2bdf8110fcc2fafd9c93418cb6962a94b51',
  'boring-linux-x64-libbssl_dart.so':
      'e3868ec00a7bbddfd08ed8e495cfa78d6dc67ce8051be9cc32225912e687eb66',
  'boring-linux-x64-libbssl_dart_static.a':
      '9e8950c45a9978445270ca8dfdcdfd07f90cc77a2395217ff5ed8fcca134d5f3',
  'boring-macos-arm64-libbssl_dart.dylib':
      '7ffe03f09f915875f773b29bdac5bf728a867590d2dd31e4f33c1e849ea0de8f',
  'boring-macos-arm64-libbssl_dart_static.a':
      '436671ed886b33f7831ab30007eef2c65d4fec8d5d8ff5b04db15ae4a70ffc02',
  'boring-macos-x64-libbssl_dart.dylib':
      'df339fa26a71388ab317c9363c7b3acc09f7f0b7021e605499370f2e826deb26',
  'boring-macos-x64-libbssl_dart_static.a':
      '743e64ab6173515135896c3031ed3ef2d5fd28c9c56f6bf8e7bb3b1ba784452f',
  'boring-windows-x64-bssl_dart.dll':
      'def0491e3f3f616c78adb6417f63ed5ca2bc734e185ddcd7bc8c4b9da961702b',
  'boring-windows-x64-bssl_dart_static.lib':
      'facfd861828143a54963b84a8da8006619b34b2a430417d40d6f4873190292f8',
};
