name: mime
version: 2.0.0
description: >-
  Utilities for handling media (MIME) types, including determining a type from
  a file extension and file contents.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/mime
topics:
 - magic-numbers
 - mime
 - mimetype
 - multipart-form

environment:
  sdk: ^3.2.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.0
