name: mime
version: 2.1.0-wip
description: >-
  Utilities for handling media (MIME) types, including determining a type from
  a file extension and file contents.
repository: https://github.com/dart-lang/tools/tree/main/pkgs/mime
issue_tracker: https://github.com/dart-lang/tools/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Amime

topics:
  - magic-numbers
  - mime
  - mimetype
  - multipart-form

environment:
  sdk: ^3.2.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  http: ^1.5.0
  path: ^1.9.0
  test: ^1.16.0
