include: package:dart_flutter_team_lints/analysis_options.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_catches_without_on_clauses
    - camel_case_types
    - prefer_single_quotes
    - unawaited_futures
