name: package:file
permissions: read-all

on:
  # Run on PRs and pushes to the default branch.
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/file.yml'
      - 'pkgs/file/**'
      - 'pkgs/file_testing/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/file.yml'
      - 'pkgs/file/**'
      - 'pkgs/file_testing/**'
  schedule:
    - cron: "0 0 * * 0"

jobs:
  correctness:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [file, file_testing]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: dev

      - name: Install ${{ matrix.package }} dependencies
        working-directory: pkgs/${{ matrix.package }}
        run: dart pub get

      - name: Verify formatting in ${{ matrix.package }}
        working-directory: pkgs/${{ matrix.package }}
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze package ${{ matrix.package }} source
        working-directory: pkgs/${{ matrix.package }}
        run: dart analyze --fatal-infos

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        package: [file]
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable, dev]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install ${{ matrix.package }} dependencies
        working-directory: pkgs/${{ matrix.package }}
        run: dart pub get

      - name: Run ${{ matrix.package }} Tests
        working-directory: pkgs/${{ matrix.package }}
        run: dart pub run test -j1
