name: package:glob
permissions: read-all

on:
  # Run CI on all PRs (against any branch) and on pushes to the main branch.
  pull_request:
    paths:
      - '.github/workflows/glob.yaml'
      - 'pkgs/glob/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/glob.yaml'
      - 'pkgs/glob/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

defaults:
  run:
    working-directory: pkgs/glob

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, dev]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: dart analyze --fatal-infos
      - run: dart format --output=none --set-exit-if-changed .
        if: ${{ matrix.sdk == 'stable' }}
      - run: dart test
