name: package:glob
permissions:
  contents: read

on:
  # Run CI on all PRs (against any branch) and on pushes to the main branch.
  pull_request:
    paths:
      - '.github/workflows/glob.yaml'
      - 'pkgs/glob/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/glob.yaml'
      - 'pkgs/glob/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

defaults:
  run:
    working-directory: pkgs/glob

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, dev]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: dart-lang/setup-dart@7654d458321ee25acccccfdb86cd48bd95768ff1
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: dart analyze --fatal-infos
      - run: dart format --output=none --set-exit-if-changed .
        if: ${{ matrix.sdk == 'stable' }}
      - run: dart test
