# Publish the markdown playground to dart-lang.github.io/tools/markdown.

name: "package:markdown: playground"

on:
  # Run on PRs and pushes to the default branch.
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/markdown_playground.yaml'
      - 'pkgs/markdown/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/markdown_playground.yaml'
      - 'pkgs/markdown/**'
    
defaults:
  run:
    working-directory: pkgs/markdown/

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: jekyll-build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
      - uses: dart-lang/setup-dart@e630b99d28a3b71860378cafdc2a067c71107f94
      
      - name: Install dependencies
        run: dart pub get

      - name: Build markdown playground
        run: dart compile js -o example/app.dart.js --minify --no-frequency-based-minification --no-source-maps example/app.dart

      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4

todo: split into 'build' and 'deploy'

