name: Dart CI

on:
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/mime.yml'
      - 'pkgs/mime/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/mime.yml'
      - 'pkgs/mime/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pkgs/mime/

    strategy:
      matrix:
        os: [ubuntu-latest]
        sdk: [3.2, dev]
    steps:
      # These are the latest versions of the github actions; dependabot will
      # send PRs to keep these up-to-date.
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dart-lang/setup-dart@e630b99d28a3b71860378cafdc2a067c71107f94

      - name: Install dependencies
        run: dart pub get
  
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test
